#' csPi class description
#'
#' csPi class description autogenerated based on /home/moi/ifremer/fishpi/fishPifct/data/csPi_v2_1.xlsx, the Tue Oct 27 13:02:00 2015.
#'
#'
#' @slot Slot SE:
#'\describe{
#' \item{recType: }{Record type (type: string).
#' Fixed value SE.}
#' \item{seCode: }{Sample event code (type: sting).
#' A unique and short code identifying the sampling event. National code. }
#' \item{dataProv: }{Data provider (type: string).
#' A means of recording who provided the data to the RDB, this may be different from the institute or body that actually did the sampling}
#' \item{sampCtry: }{Sampling country (type: string).
#' ISO 3166 – 1 alpha-3 codes. The country that did the sampling}
#' \item{sampInst: }{Sampling institution (type: NA).
#' The sampling institution, i.e. those who actually did the sampling. This might not be the organization who ultimately provide the data to the RDB.}
#' \item{sampMeth: }{Sampling method (type: string).
#' “Observer” or “SelfSampling”.}
#' \item{sampTeam: }{Sampling team (type: string).
#' An identifier for the individuals or team who collected the sample. This is likely to be mainly of interest at the national level and would be an optional field for RDB inclusion. Similar fields in the ca table could provide information on who did the age reading and should be considered.}
#' \item{seYear: }{Sampling year (type: integer).
#' Sampling event year}
#' \item{sampDate: }{Sampling date (type: string).
#' “YYYY-MM-DD” (ISO 8601).  The date on which the sampling occurred (see general issues below).}
#' \item{sampTime: }{Sampling time (type: string).
#' “HH:MM". The time on which the sampling occurred (see general issues below).}
#' \item{sampLoc: }{Sampling location (type: string).
#' The location where the sampling is done}
#' \item{sampLocType: }{Sampling location type (type: string).
#' This describes the type of location where the sampling occurred e.g. a market, a port, a vessel.}
#' \item{psuType: }{Design class (type: string).
#' This is the type of the psu and falls within the 4 classes proposed by WKPICS 2 (ICES 2012); the vessel x time, the trip, the site x day or the site. This is the unit of which psuTotal and psuSamp are measures}
#' \item{design: }{Design (type: NA).
#' This would be a character string specifying the type of sampling design used to collect the data, for example “stratified two stage cluster”. It could link specifically to the design object descriptions used in the R survey package, and would ensure that the appropriate estimation process was followed for the specific sampling data.}
#' \item{popData: }{Population Data (type: NA).
#' This would be a character string slot that allowed the specific population data from which the sample was drawn to be identified. It could be a specific link to a cpRDB object.}
#' \item{sampScheme: }{Sampling scheme (type: NA).
#' The name for the sampling scheme under which the data were collected.}
#' \item{sampStrata: }{Sampling strata (type: NA).
#' The name of the sampling stratum in the particular scheme from which the actual sample was obtained. The format of this needs discussion and/or definition.}
#' \item{sampTemporalUnit: }{Sampling Temporal Unit (type: NA).
#' The period over which the sampling is organized e.g. year, season, semester, quarter. This is the temporal sampling stratum during which sampling effort would be assumed not to change. It could include seasonal periods. This temporal period is quite distinct from a time domain, such as a quarter, for which an estimate may be needed.}
#' \item{sampTemporalId: }{Sampling Temporal Identifier (type: NA).
#' The name for temporal unit to which the data belongs. E.g. "2013" or "first season 2011" or "Qtr1 2012"}
#' \item{psuKey: }{Primary Sampling Unit key (type: NA).
#' This lists the elements in the se table that exactly allows the sampling unit to be uniquely identified. Typically it would include the scheme, the stratum, the sampling temporal identifier, the sampling date and sampling location}
#' \item{psuId: }{Primary Sampling Unit Identifier   (type: NA).
#' This is the concatenation of the actual values from the fields specified by the psuKey. These are unique to the sample, and ideally map to the elements in the population dataset (cpRDB) that can be similarly classified. The psuId would be a replicated field in all the tables in the csRDB structure.}
#' \item{psuTotal: }{Primary Sampling Unit Total   (type: NA).
#' This is the total number of possible sampling elements in the population e.g. market days over the year, vessels in the sampling frame. This would generally be obtained from the population data that is explicitly liked to the csRDB sample data. The @@$popData slot was envisaged to allow this dataset to be specifically identified.}
#' \item{psuSampled: }{Primary Sampling Unit Sampled   (type: NA).
#' This is the total number of samples obtained from within the sampling stratum and will correspond to the number of unique psuId values.}
#' \item{psuSampProb: }{Primary Sampling Unit Probability (type: NA).
#' This will be the probability of selecting the sampling unit, in many instances it will be the ratio of psuTotal/psuSampled. It could however be populated independently for example where an unequal probability selection method was used.}
#'}
#'
#' @slot Slot TR:
#'\describe{
#' \item{recType: }{Record type (type: string).
#' Fixed value TR.}
#' \item{seCode: }{Sample event code (type: sting).
#' A unique and short code identifying the sampling event. National code. }
#' \item{year: }{Year (type: integer).
#' NA}
#' \item{proj: }{Project (type: string).
#' National project name. Code list is editable.}
#' \item{trpCode: }{Trip code (type: string).
#' National coding system.?3}
#' \item{sampType: }{Sampling type (type: string).
#' “S” = sea sampling, “M” = market sampling of known fishing trips, “D” = market sampling of mixed trips, “V” = vendor. 1}
#' \item{vslFlgCtry: }{Vessel flag country (type: string).
#' ISO 3166-1 alpha-3 codes: the flag country of the vessel. This can be different from the landing country (see description of Landing country).?2}
#' \item{vslId: }{Vessel identifier (encrypted) (type: integer).
#' Encrypted vessel identifier. Id encrypted so that no-one can map the Id to the real vessel.}
#' \item{vslLen: }{Vessel length (type: integer).
#' Over-all length in metres.}
#' \item{vslLenCat: }{Vessel length category (type: string).
#' NA}
#' \item{vslPwr: }{Vessel power (type: integer).
#' Vessel power (kW)?.5}
#' \item{vslSize: }{Vessel size (type: integer).
#' Gross registered tonnes (GRT) }
#' \item{vslSizeUnit: }{Vessel size unit (type: string).
#' A new field for the vessel size unit, gross tonnage GT and gross registered tonnage GRT are used for different sizes of vessels and are not readily convertible.}
#' \item{vslType: }{Vessel type (type: integer).
#' 1=stern trawler, 2=side trawler, 3=gillnetter, 4=other boats.}
#' \item{foNum: }{Number of sets/hauls on trip (type: integer).
#' Total number of hauls/sets taken during the trip. Both the stations where biological measures were taken and the stations that were not worked up should be counted here.?8}
#' \item{daysAtSea: }{Days at sea (type: integer).
#' In days.?9}
#' \item{voyageId: }{Voyage identifier (type: string).
#' A new field for voyage identifier. This would provide a direct link to control agency data and can be the fishing trip ID or landing ID. It would provide a link between the population data and the sampling frame}
#' \item{depLoc: }{Departure location (type: string).
#' NA}
#' \item{depDate: }{Depature date (type: string).
#' “YYYY-MM-DD” (ISO 8601). The date of departure of the trip}
#' \item{depTime: }{Departure time (type: string).
#' "HH:MM". The time of departure of the trip.}
#' \item{arvLoc: }{Arrival location (type: string).
#' NA}
#' \item{arvDate: }{Arrival date (type: string).
#' “YYYY-MM-DD” (ISO 8601). The date of arrival of the trip.}
#' \item{arvTime: }{Arrival time (type: string).
#' "HH:MM". The arrival time of the trip.}
#' \item{ssuType: }{Secondary sampling unit Type (type: string).
#' The type of secondary sampling unit, e.g. this could be vessels landing at a market on a particular day in the case of onshore sampling, or a fishing trip of a particular vessel in the at-sea case. Analogous to the use of psuType in the se table. }
#' \item{ssuKey: }{Secondary sampling unit key (type: string).
#' Secondary sampling unit key. The variables used to identify the secondary sampling unit, typically this would be the pusId and the unique identifier for the secondary unit e.g. the vessel or the trip.}
#' \item{ssuId: }{Secondary sampling unit Identifier (type: string).
#' The secondary sampling unit identifier; the actual values as specified by the ssuKey.}
#' \item{ssuTotal: }{Secondary sampling unit total (type: string).
#' The total number of secondary sampling units, for example the number of vessels landing at a market on a particular day, or the total number of fishing trips made by a particular fishing vessel. }
#' \item{ssuSampled: }{Secondary sampling unit sampled (type: string).
#' The number of secondary sampling units actually sampled, e.g. the total number of different vessels sampled at a market on a particular day in the case of an onshore sample. For an at-sea sample this will be the number of trips sampled from the particular vessel. }
#' \item{ssuSampProb: }{Secondary sampling unit probability (type: string).
#' The sampling probability for the secondary sampling unit. i.e the ratio of ssuTotal/ssuSampled.}
#'}
#'
#' @slot Slot HH:
#'\describe{
#' \item{recType: }{Record type (type: string).
#' Fixed value HH.}
#' \item{seCode: }{Sample event code (type: sting).
#' A unique and short code identifying the sampling event. National code. }
#' \item{year: }{Year (type: integer).
#' NA}
#' \item{proj: }{Project (type: string).
#' National project name. Code list is editable.}
#' \item{trpCode: }{Trip code (type: string).
#' National coding system.}
#' \item{aggLev: }{Aggregation level (type: string).
#' H=haul. T=trip.}
#' \item{landFrac: }{Landing fraction (type: NA).
#' The landed fraction. This is a means of identifying sections of the landing that can be distinguished that are not fishing operations. Typically this could relate to different parts of a landing that came from different sea areas or were caught using a different gears on the same trip. Suitable codes would need to be determined. }
#' \item{staNum: }{Station number (type: integer).
#' Sequential numbering by trip.}
#' \item{foType: }{Fishing Operation Type (type: NA).
#' The type of fishing operation recorded, e.g. could be a haul or a set, or it could be used for purse-seines fishing for Tuna around a fish aggregation device (FAD) or as a free school. In the case of an onshore sample it could be the nature of the landed fraction.}
#' \item{foKey: }{Fishing Operation Key (type: NA).
#' The means of identifying the specific fishing operations; e.g. trip and haul number, in the onshore case market day vessel and landed fraction.}
#' \item{foId: }{Fishing Operation Identifier (type: NA).
#' Fishing operation Identifier; this would be the specific identifier for the fishing operation, as specified by the foKey.}
#' \item{foVal: }{Fishing validity (type: string).
#' I=Invalid. V=Valid.}
#' \item{catReg: }{Catch registration (type: string).
#' The catch registration. An existing field that was unclear. Registers what components of the catch can be expected in the sl tables. The parts (landings/discards) of the catch are registered as "All", "Lan", "Dis", "Non". According to current definitions "All" assumes that both "Lan" and "Dis" are sampled. Do we need a category for Catch samples?}
#' \item{sppReg: }{Species registration (type: string).
#' The species in the catch, registered as "All", "Par", "Non".}
#' \item{foDate: }{Date (type: string).
#' Date. This would be defined according to the fishing operation, and the subgroup considered that it should become foDate. There might however be database issues in the changing of a field name.}
#' \item{foTime: }{Time (type: string).
#' Starting time. "HH:MM"… in UTC.?9}
#' \item{foDur: }{Fishing duration (type: integer).
#' In minutes.10}
#' \item{latIni: }{Pos.Start.Lat.dec. (type: dec(5)).
#' Shooting (start) position in decimal degrees of latitude.?11 }
#' \item{lonIni: }{Pos.Start.Lon.dec. (type: dec(5)).
#' Shooting (start) position in decimal degrees of longitude?.11}
#' \item{latFin: }{Pos.Stop.Lat.dec. (type: dec(5)).
#' Hauling (stop) position in decimal degrees of latitude?.11}
#' \item{lonFin: }{Pos.Stop.Lon.dec. (type: dec(5)).
#' Hauling (stop) position in decimal degrees of longitude.?11}
#' \item{ecoZone: }{Economical zone (type: NA).
#' The economic zone. An additional spatial variable that can be used to identify areas beyond the ICES divisions.}
#' \item{area: }{Area (type: string).
#' Area level 3 (level 4 for Baltic, Mediterranean, and Black Seas) in the Data Collection Regulation (EC, 2008a, 2008b).}
#' \item{rect: }{Statistical rectangle (type: string).
#' Area level 5 in the Data Collection Regulation (EC, 2008a, 2008b). This is the ICES statistical rectangles (e.g. 41G9) except for the Mediterranean and Black Seas, where GFCM geographical subareas (GSAs) are used.?13}
#' \item{subRect: }{Subpolygon (type: string).
#' National level as defined by each country as child nodes (substratification) of the ICES rectangles. It is recommended that this is coordinated internationally, e.g. through the Regional Coordination Meetings (EC RCMs).}
#' \item{foDep: }{Main fishing depth (type: integer).
#' Depth from surface to groundrope in metres?.5}
#' \item{waterDep: }{Main water depth (type: integer).
#' Depth from surface in metres?.14}
#' \item{foCatNat: }{Fishing activity category National (type: string).
#' Country specific Fishing activity category (=?métier). National level as defined by each country as child nodes (substratification) of the level-5 codes.}
#' \item{foCatEu5: }{Fishing activity category European lvl 5 (type: string).
#' Fishing activity category (=?métier). Level 5 as defined in a hierarchic structure in the Data Collection Regulation (EC, 2008a, 2008b).}
#' \item{foCatEu6: }{Fishing activity category European lvl 6 (type: string).
#' Fishing activity category. Level 6 as defined in a hierarchic structure in the Data Collection Regulation (EC, 2008a, 2008b). Level 6 is further specified by the Regional Coordination Meetings (EC RCMs, Council Regulation [EC] No 1543/2000) or any later authorized revision.}
#' \item{gear: }{Gear type (type: streng).
#' NA}
#' \item{meshSize: }{Mesh size (type: integer).
#' Stretch measure.?18}
#' \item{selDev: }{Selection device (type: integer).
#' Not mounted?=?0, Exit window / selection panel?=?1, grid?=?2. A selection device is defined as a square-meshed panel or window that is inserted into a towed net.}
#' \item{meshSizeSelDev: }{Mesh size in selection device (type: integer).
#' In mm. The mesh size of a square-meshed panel or window shall mean the largest determinable mesh size of such a panel or window.}
#' \item{landCtry: }{Landing country (type: string).
#' ISO 3166-1 alpha-3 codes}
#' \item{landLoc: }{Landing location (type: NA).
#' The landing location. A more clearly defined field for the landing harbour. One problem with having harbour in the tr table is that it assumes that a single trip has a single landing port, this may not be the case.}
#' \item{landLocType: }{Landing location type (type: NA).
#' The landing location type. This would be a descriptor of the landing location, suggested by the subgroup and could be used to distinguish ports, auctions, fish cages,factory ships etc.}
#' \item{landDate: }{Landings date (type: NA).
#' The date of the landing. Note that there would be a arrival date (in TR) and a separate landing date (in HH), with the possibility that there may be more than one landing for a single fishing trip. This is to reflect the situation found with some fishing trips which have multiple landings.}
#' \item{landTime: }{Landing time (type: NA).
#' NA}
#' \item{saleCtry: }{Sales country (type: NA).
#' The sale location of the landed fraction of the catch.}
#' \item{saleLoc: }{Sales location (type: NA).
#' The sale country of the landed fraction of the catch.}
#' \item{saleDate: }{Sales date (type: NA).
#' The sale date of the landed fraction of the catch.}
#' \item{saleTime: }{Sales time (type: NA).
#' NA}
#' \item{buyerLoc: }{Buyer location (type: NA).
#' The buyer's location. This is a potential sampling location that is distinct from both the landing location and the sale location.}
#' \item{domain1: }{Domain 1 (type: NA).
#' NA}
#' \item{domain2: }{Domain 2  (type: NA).
#' NA}
#' \item{foTotal: }{Fishing Operation Total  (type: NA).
#' The fishing operation total, e.g. the total number of hauls on a trip. How this would work for the landFrac needs to be tested.}
#' \item{foSampled: }{Fishing Operation Sampled  (type: NA).
#' The number of fishing operations sampled.}
#' \item{foSampProb: }{Fishing Operation Probability (type: NA).
#' The fishing operation sampling probability, this would usually be the ratio of foTotal/foSamp and the sample weight, for the fishing operation, would be the inverse of foSampProb. foTotal, foSamp and foSampProb are analogous to the sampling probability variables for the psu and ssu in the SE and TR tables.}
#'}
#'
#' @slot Slot SL:
#'\describe{
#' \item{recType: }{Record type (type: string).
#' Fixed value SL.}
#' \item{seCode: }{Sample event code (type: sting).
#' A unique and short code identifying the sampling event. National code. }
#' \item{year: }{Year (type: integer).
#' NA}
#' \item{proj: }{Project (type: string).
#' National project name. Code list is editable.}
#' \item{trpCode: }{Trip code (type: string).
#' National coding system.}
#' \item{staNum: }{Station number (type: integer).
#' Sequential numbering by trip.}
#' \item{foId: }{Fishing operation Identifier (type: NA).
#' Fishing operation Identifier; this would be the specific identifier for the fishing operation, as specified by the foKey.}
#' \item{commSpp: }{Commercial species (type: NA).
#' The commercial species. These are how the commercial data are likely to be recorded officially - these will include landings where species are not commercially identified but landed collectively and in some case might not be correct (Anglerfish, megrim, gurnards, sole, skates and rays). This would allow the observer(s) to identify the species within a commercial species mix when sampling.}
#' \item{spp: }{Species (type: string).
#' Scientific name in Latin (Genus species). (A suffix to the latin name  is used for species for which Stock cannot be defined by area)}
#' \item{catchCat: }{Catch category (type: string).
#' The fate of the catch: "Dis"=discard, "Lan"=landing.}
#' \item{landCat: }{Landing category (type: string).
#' The intended usage at the time of landing. This should match the same field in CL record (whether or not the fish was actually used for this or another purpose): "IND"=industry or "HUC"=human consumption.}
#' \item{commCatScl: }{Commercial size category scale (type: string).
#' Commercial sorting scale code (optional for "Unsorted"). }
#' \item{commCat: }{Commercial size category (type: integer).
#' Commercial sorting category in the given scale (optional for "Unsorted"). (EC, 2006) and later amendments when scale is "EU".}
#' \item{subSampCat: }{Subsampling category (type: string).
#' Used when different fractions of the same species are subsampled at different levels. Typically used when few large specimens are taken out from the total catch before the many small fish are subsampled.}
#' \item{sex: }{Sex (type: string).
#' M=Male, F=Female, T=Transitional2 (optional for "Unsexed").}
#' \item{unitType: }{Unit type (type: NA).
#' The type of sampling unit. This would define the sampling unit at the sl level, and could be be for example a box of fish, a section of net, a basket of mixed discards}
#' \item{unitKey: }{Unit Key  (type: NA).
#' The sampling unit key would be the variables that allowed the sampling unit to be uniquely identified.}
#' \item{unitId: }{Unit Identifier (type: NA).
#' The sampling unit identifier, the actual value of the sampling unit as specified by the unitKey.}
#' \item{wt: }{Weight (type: integer).
#' Whole weight in grammes. Decimals not allowed. Weight of the corresponding stratum (Species - Catch category - size category - Sex).}
#' \item{subSampWt: }{Subsample weight (type: integer).
#' Whole weight in grammes. Decimals not allowed. For sea sampling: the live weight of the subsample of the corresponding stratum. For market sampling: the sample weight is the whole weight of the fish measured (e.g. the summed weight of the fish in one or more boxes).}
#' \item{totWtDeriv: }{Total weight derivation  (type: NA).
#' The total weight derivation. At present there is a wt field in the SL table defined as the whole weight in grams. How that weight is obtained can in practice vary considerably and the weight derivation field seeks to identify that. Weights can be obtained from actual measures, estimates derived from observers or fishing vessel crew, official logbook records, official auction weights, or extrapolated from the weight length relationships of measured individuals.}
#' \item{sampWtDeriv: }{Sampling Weight Derivation  (type: NA).
#' The sample weight derivation. As with the total weight this field seeks to clarify how the sample weight is actually derived. These can, for instance, be measured weights by observers of individual or groups of fish, measured weights by fishing vessel crew or official box weights, they can be obtained from weight length relationships of fish that are measured, but not weighed.}
#' \item{measType: }{Measurement Type (type: NA).
#' The measurement type. This would be used to describe what parameter was measured e.g. width, tail, head, folk length and is related to the measure class and measure number fields in the HL table.}
#' \item{pres: }{Presentation (type: NA).
#' Presentation; the condition in which the sample was presented, e.g. gutted, whole, headless etc. The presentation will be related to the commercial category but can differ within a single commercial category. This is pertinent to the weight fields.}
#' \item{convFacWt: }{Conversion Factor Weight (type: NA).
#' The conversion factor used to get from the presentation to the whole weight (wt) field in the sl table.}
#' \item{lenCode: }{Length code (type: string).
#' Class: 1?mm?=?"mm", 0.5?cm?=?"scm"; 1?cm?=?"cm"; 2.5?cm?=?25?mm", 5?cm?=?"5?cm".}
#' \item{unitTotal: }{Sampling Unit Total  (type: NA).
#' The sampling unit total, e.g. the total number of boxes, baskets, etc. used to quantify the sampling unit.}
#' \item{unitSampled: }{Sampling Units Sampled   (type: NA).
#' The number of sampling units sampled.}
#' \item{unitSampProb: }{Sampling Unit Probability (type: NA).
#' The sampling unit probability, this would usually be the ratio of unitTotal/unitSamp and the sample weight, for the sampling unit, would be the inverse of unitSampProb. These fields are analogous to the sampling probability variables in the SE, TR, and HH tables.}
#'}
#'
#' @slot Slot HL:
#'\describe{
#' \item{recType: }{Record type (type: string).
#' Fixed value HL.}
#' \item{seCode: }{Sample event code (type: sting).
#' A unique and short code identifying the sampling event. National code. }
#' \item{year: }{Year (type: integer).
#' NA}
#' \item{proj: }{Project (type: string).
#' National project name. Code list is editable.}
#' \item{trpCode: }{Trip code (type: string).
#' National coding system.}
#' \item{staNum: }{Station number (type: integer).
#' Sequential numbering by trip.}
#' \item{foId: }{Fishing operation Identifier (type: NA).
#' Fishing operation Identifier; this would be the specific identifier for the fishing operation, as specified by the foKey.}
#' \item{spp: }{Species (type: string).
#' Scientific name in Latin (Genus species). (A suffix to the latin name  is used for species for which Stock cannot be defined by area)}
#' \item{catchCat: }{Catch category (type: string).
#' The fate of the catch: "Dis"=discard, "Lan"=landing.}
#' \item{landCat: }{Landing category (type: string).
#' The intended usage at the time of landing. This should match the same field in CL record (whether or not the fish was actually used for this or another purpose): "IND"=industry or "HUC"=human consumption.}
#' \item{commCatScl: }{Commercial size category scale (type: string).
#' Commercial sorting scale code (optional for "Unsorted"). }
#' \item{commCat: }{Commercial size category (type: integer).
#' Commercial sorting category in the given scale (optional for "Unsorted"). (EC, 2006) and later amendments when scale is "EU".}
#' \item{subSampCat: }{Subsampling category (type: string).
#' Used when different fractions of the same species are subsampled at different levels. Typically used when few large specimens are taken out from the total catch before the many small fish are subsampled.}
#' \item{sex: }{Sex (type: string).
#' M=Male, F=Female, T=Transitional2 (optional for "Unsexed").}
#' \item{unitId: }{Unit Identifier (type: NA).
#' The sampling unit identifier, the actual value of the sampling unit as specified by the unitKey.}
#' \item{indSex: }{Individual sex (type: string).
#' The individual sex field allows the sample of a species to be split by sex after being sampled e.g. Rays, Nephrops. This allows a sex specific length distribution to be recorded. This was a point of clarity for the subgroup as to why this field was needed, it is an existing field and there would be no change to its use. Compare with the sex field in the sl table.}
#' \item{lenCls: }{Length class (type: integer).
#' In mm. Identifier: lower bound of size class, e.g. 650 for 65?-?66?cm.}
#' \item{lenNum: }{Number at length (not raised to whole catch) (type: integer).
#' Length classes with zero should be excluded from the record.}
#' \item{measType: }{Measurement type (type: NA).
#' The measurement type field might need to be in this table. This is, as with the HL table, the parameter recorded e.g. fork length, max length, shell height; see the rationale for measType in the sl table.}
#' \item{measCls: }{Measurement class (type: NA).
#' The measurement class. This would be the measurement value taken on the sampled individuals. It could be an alternative or additional measure to the length, which can already be recorded in the HL table. The measurement class would relate to the measType field in the SL table. Examples could be tail widths of Nephrops in mm, carapace lengths, and carapace widths.}
#' \item{measNum: }{Measurment Number (type: NA).
#' The number of individuals at the specified measurement class. This is a new field. measCls and measNum are analogous to the existing lenCls and LenNum for the recording of length frequency distributions.}
#' \item{convFacLen: }{Conversion Factor Length (type: NA).
#' A new field; the conversion factor needed to get from the parameter measured to a standard length. For example the value used to get from the measure to the length class such as Nephrops tails X 3 = carapace length. This conversion factor can be length dependent therefore it has to be in the hl table with the length class.}
#' \item{fishTotal: }{Fish Total (type: NA).
#' The total number of fish (or shellfish), e.g. the total number of fish within the sample such as a box or basket.}
#' \item{fishSampled: }{Fish Measured (type: NA).
#' The number of fish (or shellfish) measured, e.g. the number of fish for which length or another measure was made from within the sample.}
#' \item{fishSampProb: }{Fish Sampling Probability (type: NA).
#' The sampling probability for the measured fish, this would usually be the ratio of fishTotal/fishSamp and the sample weight, for the measured fish would be the inverse of fishSampProb. These fields are analogous to the sampling probability variables in the SE, TR, and HH and SL tables.}
#'}
#'
#' @slot Slot CA:
#'\describe{
#' \item{recType: }{Record type (type: string).
#' Fixed value CA.}
#' \item{seCode: }{Sample event code (type: sting).
#' A unique and short code identifying the sampling event. National code. }
#' \item{year: }{Year (type: integer).
#' NA}
#' \item{proj: }{Project (type: string).
#' National project name. Code list is editable.}
#' \item{trpCode: }{Trip code (type: string).
#' National coding system.?3}
#' \item{staNum: }{Station number (type: integer).
#' Sequential numbering by trip.}
#' \item{foId: }{Fishing Operation Identifier (type: NA).
#' NA}
#' \item{quarter: }{Quarter (type: integer).
#' NA}
#' \item{month: }{Month (type: integer).
#' NA}
#' \item{spp: }{Species (type: string).
#' Scientific name in Latin (Genus species). A suffix to the latin name  is used for species for which Stock cannot be defined by area)}
#' \item{sex: }{Sex (type: string).
#' M=Male, F=Female, T=Transitional2 (optional for "Unsexed").}
#' \item{unitId: }{Unit Identifier (type: NA).
#' NA}
#' \item{indSex: }{Individual sex (type: NA).
#' NA}
#' \item{catchCat: }{Catch category (type: string).
#' The fate of the catch: discard or landing.}
#' \item{landCat: }{Landing category (type: string).
#' The intended usage at the time of landing. This should match the same field in the LS record (whether or not the fish was actually used for this or another purpose): industry or human consumption.}
#' \item{commCatScl: }{Commercial size category scale (type: string).
#' Commercial sorting scale code (optional for "Unsorted").}
#' \item{commCat: }{Commercial size category (type: integer).
#' Commercial sorting category in the given scale. (optional for "Unsorted").}
#' \item{subSampCat: }{Subsampling category (type: NA).
#' NA}
#' \item{stock: }{Stock (type: string).
#' 3}
#' \item{area: }{Area (type: string).
#' Area level 3 (level 4 for Baltic, Mediterranean, and Black Seas) in the Data Collection Regulation (EC, 2008a, 2008b).}
#' \item{rect: }{Statistical rectangle (type: string).
#' Area level 5 in the Data Collection Regulation (EC, 2008a, 2008b). This is the ICES statistical rectangles (e.g. 41G9) except for the Mediterranean and Black Seas where GFCM geographical subareas (GSAs) are used.}
#' \item{subRect: }{Subpolygon (type: string).
#' National level as defined by each country as child nodes (substratification) of the ICES rectangles. It is recommended that this is coordinated internationally, e.g. through the Regional Coordination Meetings (EC RCMs).}
#' \item{lenCls: }{Length class (type: integer).
#' In mm. Identifier: lower bound of size class, e.g. 650 for 65?-66?cm.}
#' \item{age: }{Age (type: integer).
#' Estimated age.}
#' \item{fishId: }{Single fish number (id) (type: integer).
#' National numbering system of the individual fish. Preferably unique within the given Station and Species, but necessarily unique for the given combination of key fields above.}
#' \item{lenCode: }{Length code (type: integer).
#' Class: 1mm="mm", 0.5cm="scm"; 1cm="cm"; 2.5cm="25mm", 5cm="5cm".}
#' \item{measType: }{Measurement Type (type: NA).
#' The measurement type field might need to be in this table. This is, as with the HL table, the parameter recorded e.g. fork length, max length, shell height; see the rationale for measType in the sl table.}
#' \item{measCls: }{Measurement Class (type: NA).
#' The measurement class might need to be in this table, as well as the length class, to indicate the increment and size of the measurements, see the rationale for measCls in the hl table length groups.}
#' \item{fishAtLengthTotal: }{Fish at length total (type: NA).
#' The total number of fish/shellfish measured (for length).}
#' \item{fishAtlengthSampled: }{Fish at length Sampled  (type: NA).
#' The total number of fish/shellfish sampled for age weight maturity.}
#' \item{individualFishSampProb: }{Individual Fish Sampling Probability (type: NA).
#' The sampling probability of the fish/shellfish sampled for age weight maturity.}
#' \item{ageMeth: }{Aging method (type: string).
#' Methodology for estimating the age.}
#' \item{plusGrp: }{Age-plus-group (type: string).
#' +?=?Plus group, ??=?Not plus group.6}
#' \item{otoWt: }{Otolith weight (type: dec(5)).
#' In grammes.}
#' \item{otoSide: }{Otolith side (type: string).
#' The side of the fish where the otolith was taken. R?=?right, L?=?left.}
#' \item{indWt: }{Weight (type: dec(1)).
#' In grammes.}
#' \item{matMeth: }{Maturity staging method (type: string).
#' Methodology for estimating the maturity stage.}
#' \item{matScale: }{Maturity scale (type: string).
#' The maturity scale gives the range of the possible stages (values).}
#' \item{matStage: }{Maturity stage (type: string).
#' The stage (value) in the given scale.}
#'}
#'
#' @name csPi
#' @exportClass csPi
#'
###
# generated on 2015-10-27 13:02:00
###

setClass(
	Class="csPi",
	slots=list(
		classVersion="character",
		desc="character",
		popData="character",
		design="character",
		history="character",
		se="data.frame",
		tr="data.frame",
		hh="data.frame",
		sl="data.frame",
		hl="data.frame",
		ca="data.frame"
	),
	prototype=list(
		classVersion="2.1",
		desc="Commercial Sampling Data format for the fishPi project",
		popData="Named population data object",
		design="Design description",
		history="modification history",
		se=data.frame(
			recType=character(), 
			seCode=character(), 
			dataProv=character(), 
			sampCtry=character(), 
			sampInst=character(), 
			sampMeth=character(), 
			sampTeam=character(), 
			seYear=integer(), 
			sampDate=character(), 
			sampTime=character(), 
			sampLoc=character(), 
			sampLocType=character(), 
			psuType=character(), 
			design=character(), 
			popData=character(), 
			sampScheme=character(), 
			sampStrata=character(), 
			sampTemporalUnit=character(), 
			sampTemporalId=character(), 
			psuKey=character(), 
			psuId=character(), 
			psuTotal=character(), 
			psuSampled=character(), 
			psuSampProb=character()
		), 
		tr=data.frame(
			recType=character(), 
			seCode=character(), 
			year=integer(), 
			proj=character(), 
			trpCode=character(), 
			sampType=character(), 
			vslFlgCtry=character(), 
			vslId=integer(), 
			vslLen=integer(), 
			vslLenCat=character(), 
			vslPwr=integer(), 
			vslSize=integer(), 
			vslSizeUnit=character(), 
			vslType=integer(), 
			foNum=integer(), 
			daysAtSea=integer(), 
			voyageId=character(), 
			depLoc=character(), 
			depDate=character(), 
			depTime=character(), 
			arvLoc=character(), 
			arvDate=character(), 
			arvTime=character(), 
			ssuType=character(), 
			ssuKey=character(), 
			ssuId=character(), 
			ssuTotal=character(), 
			ssuSampled=character(), 
			ssuSampProb=character()
		), 
		hh=data.frame(
			recType=character(), 
			seCode=character(), 
			year=integer(), 
			proj=character(), 
			trpCode=character(), 
			aggLev=character(), 
			landFrac=character(), 
			staNum=integer(), 
			foType=character(), 
			foKey=character(), 
			foId=character(), 
			foVal=character(), 
			catReg=character(), 
			sppReg=character(), 
			foDate=character(), 
			foTime=character(), 
			foDur=integer(), 
			latIni=double(), 
			lonIni=double(), 
			latFin=double(), 
			lonFin=double(), 
			ecoZone=character(), 
			area=character(), 
			rect=character(), 
			subRect=character(), 
			foDep=integer(), 
			waterDep=integer(), 
			foCatNat=character(), 
			foCatEu5=character(), 
			foCatEu6=character(), 
			gear=character(), 
			meshSize=integer(), 
			selDev=integer(), 
			meshSizeSelDev=integer(), 
			landCtry=character(), 
			landLoc=character(), 
			landLocType=character(), 
			landDate=character(), 
			landTime=character(), 
			saleCtry=character(), 
			saleLoc=character(), 
			saleDate=character(), 
			saleTime=character(), 
			buyerLoc=character(), 
			domain1=character(), 
			domain2=character(), 
			foTotal=character(), 
			foSampled=character(), 
			foSampProb=character()
		), 
		sl=data.frame(
			recType=character(), 
			seCode=character(), 
			year=integer(), 
			proj=character(), 
			trpCode=character(), 
			staNum=integer(), 
			foId=character(), 
			commSpp=character(), 
			spp=character(), 
			catchCat=character(), 
			landCat=character(), 
			commCatScl=character(), 
			commCat=integer(), 
			subSampCat=character(), 
			sex=character(), 
			unitType=character(), 
			unitKey=character(), 
			unitId=character(), 
			wt=integer(), 
			subSampWt=integer(), 
			totWtDeriv=character(), 
			sampWtDeriv=character(), 
			measType=character(), 
			pres=character(), 
			convFacWt=character(), 
			lenCode=character(), 
			unitTotal=character(), 
			unitSampled=character(), 
			unitSampProb=character()
		), 
		hl=data.frame(
			recType=character(), 
			seCode=character(), 
			year=integer(), 
			proj=character(), 
			trpCode=character(), 
			staNum=integer(), 
			foId=character(), 
			spp=character(), 
			catchCat=character(), 
			landCat=character(), 
			commCatScl=character(), 
			commCat=integer(), 
			subSampCat=character(), 
			sex=character(), 
			unitId=character(), 
			indSex=character(), 
			lenCls=integer(), 
			lenNum=integer(), 
			measType=character(), 
			measCls=character(), 
			measNum=character(), 
			convFacLen=character(), 
			fishTotal=character(), 
			fishSampled=character(), 
			fishSampProb=character()
		), 
		ca=data.frame(
			recType=character(), 
			seCode=character(), 
			year=integer(), 
			proj=character(), 
			trpCode=character(), 
			staNum=integer(), 
			foId=character(), 
			quarter=integer(), 
			month=integer(), 
			spp=character(), 
			sex=character(), 
			unitId=character(), 
			indSex=character(), 
			catchCat=character(), 
			landCat=character(), 
			commCatScl=character(), 
			commCat=integer(), 
			subSampCat=character(), 
			stock=character(), 
			area=character(), 
			rect=character(), 
			subRect=character(), 
			lenCls=integer(), 
			age=integer(), 
			fishId=integer(), 
			lenCode=integer(), 
			measType=character(), 
			measCls=character(), 
			fishAtLengthTotal=character(), 
			fishAtlengthSampled=character(), 
			individualFishSampProb=character(), 
			ageMeth=character(), 
			plusGrp=character(), 
			otoWt=double(), 
			otoSide=character(), 
			indWt=double(), 
			matMeth=character(), 
			matScale=character(), 
			matStage=character()
		)
	)
)

#' @export
piPk <- function(table){
	if (table=="se") return(c("seCode"))
	if (table=="tr") return(c("seCode", "year", "proj", "trpCode"))
	if (table=="hh") return(c("seCode", "year", "proj", "trpCode", "staNum", "foId"))
	if (table=="sl") return(c("seCode", "year", "proj", "trpCode", "staNum", "foId", "spp", "catchCat", "landCat", "commCatScl", "commCat", "subSampCat", "sex", "unitId"))
	if (table=="hl") return(c("seCode", "year", "proj", "trpCode", "staNum", "foId", "spp", "catchCat", "landCat", "commCatScl", "commCat", "subSampCat", "sex", "unitId", "indSex", "lenCls", "measType", "measCls"))
	if (table=="ca") return(c("seCode", "year", "proj", "trpCode"))
}
